#hyperparameter tuning 
defaults:
  - override hydra/sweeper: nevergrad

hydra:
  sweeper:
    optim:
      # name of the nevergrad optimizer to use
      # OnePlusOne is good at low budget, but may converge early
      optimizer: OnePlusOne
      # total number of function evaluations to perform
      budget: 100
      # number of parallel workers for performing function evaluations
      num_workers: 1
      # maximize: true  # comment out for maximization
    # default parametrization of the search space
    parametrization:
      datasets.freihand.bs:
        lower: 4
        upper: 5
        integer: true
      datasets.freihand.model.encoder.nhead:
        lower: 1
        upper: 8
        integer: true
      datasets.freihand.model.encoder.num_layers:
        lower: 1
        upper: 8
        integer: true

# ****** end of hyper parameter tuning****

data_dir: C:\Users\lahir\Downloads\
dataset: freihand
# mode: training or evaluation
mode: [training]
#if true, try to use the GPU if available. false: do not use GPU even if its availabel
use_gpu: true

train:
  dataset: freihand
  num_thread: 0
  lr: 0.001
  lr_drop: 
  lr_dec_factor: 0.5
  lr_decay_step: 100
  n_epochs: 1
  eval_freq: 1
  #parameters for how to incorporate hand dimentions
  hand_dim:
    use_hand_dim: true
    early_fusion: false
    early_embed_fusion: true
    late_fusion: false

datasets:
  freihand:
    base_path: 'C:\\Users\\lahir\\Downloads\\'
    version: gs
    get_mask: False
    get_image: True
    unet_annot: True
    bs : 12
    num_joints: 21
    personal_embed_dim: 128
    model: 
      pos_mask_size: 224
      encoder:
        nhead : 2
        dim_feedforward: 100
        dropout: 0.2
        num_layers: 2
        #this is for a single dimention. *2 for the full positional embedding
        pos_embed_dim: 16
        joint_embed_dim: 224
        #d_model = pose_embed*2 + joint_embed
      
    joint_idx:
      root : 0
      little: 
        mcp: 1
        pip: 2
        dip: 3
        tip: 4
      ring:
        mcp: 5
        pip: 6
        dip: 7
        tip: 8
      middle:
        mcp: 9
        pip: 10
        dip: 11
        tip: 12
      index:
        mcp: 13
        pip: 14
        dip: 15
        tip: 16
      thumb:
        mcp: 17
        pip: 18
        dip: 19
        tip: 20


